# Generated by Django 4.0 on 2021-12-10 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='palabras',
            name='texto',
            field=models.CharField(default='', max_length=9999999),
        ),
        migrations.AlterField(
            model_name='palabras',
            name='url',
            field=models.CharField(default='', max_length=99999),
        ),
    ]
